;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname Exercise-026-MovieTheatreV4) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp")))))
; Exercise 26. 
; Define constants for the price optimization program so that the price 
; sensitivity of attendance (15 people for every 10 cents) becomes a computed
; constant.

; Constants
(define AVG_ATTENDENCE    120)
(define BASE_TICKET_PRICE   5.0)
(define PEOPLE_SWING 15)
(define PRICE_VARIANCE 0.1)
(define PRICE_SENSITIVITY (/ PEOPLE_SWING PRICE_VARIANCE))
(define VARIABLE_COSTS 1.50)

; # of attendees is based on ticket price
(define (attendees ticket-price)  
  (- AVG_ATTENDENCE (* (- ticket-price BASE_TICKET_PRICE) 
                       PRICE_SENSITIVITY)))

; revenue generated by ticket sales
(define (revenue ticket-price) 
  (* ticket-price (attendees ticket-price)))

; cost has a fixed part and a variable part based on the number of attendees
(define (cost ticket-price)  
  (* VARIABLE_COSTS (attendees ticket-price)))

; profit
(define (profit ticket-price) 
  (- (revenue ticket-price)     
     (cost ticket-price)))

(profit 3.0)
(profit 4.0)
(profit 5.0)
