;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname Exercise-023-MovieTheatreV1) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp")))))
; Exercise 23.
; Our solution to the sample problem contains several constants in the middle 
; of functions. As One Program, Many Definitions already points out, it is 
; best to give names to such constants so that future readers understand where 
; these numbers come from. Collect all definitions in DrRacket’s definitions 
; area and change them so that all magic numbers are refactored into constant
; definitions.

; Constants
(define AVG_ATTENDENCE    120)
(define BASE_TICKET_PRICE   5.0)
(define PEOPLE_SWING 15)
(define PRICE_VARIANCE 0.1)
(define FIXED_COSTS 180.0)
(define VARIABLE_COSTS 0.04)

; # of attendees is based on ticket price
(define (attendees ticket-price)  
  (- AVG_ATTENDENCE (* (- ticket-price BASE_TICKET_PRICE) 
                       (/ PEOPLE_SWING PRICE_VARIANCE))))

; revenue generated by ticket sales
(define (revenue ticket-price) 
  (* ticket-price (attendees ticket-price)))

; cost has a fixed part and a variable part based on the number of attendees
(define (cost ticket-price)  
  (+ FIXED_COSTS (* VARIABLE_COSTS (attendees ticket-price))))

; profit
(define (profit ticket-price) 
  (- (revenue ticket-price)     
     (cost ticket-price)))

; example usage
(profit 5.0)
(profit 5.10)
(profit 4.90)
