;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname Exercise-024-MovieTheatreV3) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp")))))
; Exercise 25. 
; After studying the costs of a show, the owner discovered several ways of 
; lowering the cost. As a result of his improvements, he no longer has a 
; fixed cost. He now simply pays $1.50 per attendee.
;
; Modify both programs to reflect this change. When the programs are modified,
; test them again with ticket prices of $3, $4, and $5 and compare the results. 

; Constants
(define AVG_ATTENDENCE    120)
(define BASE_TICKET_PRICE   5.0)
(define PEOPLE_SWING 15)
(define PRICE_VARIANCE 0.1)
(define VARIABLE_COSTS 1.50)

; # of attendees is based on ticket price
(define (attendees ticket-price)  
  (- AVG_ATTENDENCE (* (- ticket-price BASE_TICKET_PRICE) 
                       (/ PEOPLE_SWING PRICE_VARIANCE))))

; revenue generated by ticket sales
(define (revenue ticket-price) 
  (* ticket-price (attendees ticket-price)))

; cost has a fixed part and a variable part based on the number of attendees
(define (cost ticket-price)  
  (* VARIABLE_COSTS (attendees ticket-price)))

; profit
(define (profit ticket-price) 
  (- (revenue ticket-price)     
     (cost ticket-price)))

(profit 3.0)
(profit 4.0)
(profit 5.0)

; revised alternative function
(define (alt-profit price) 
  (- (* (+ 120 (* (/ 15 0.1) (- 5.0 price)))  price)
     (* 1.50 (+ 120 (* (/ 15 0.1) (- 5.0 price))))))

(alt-profit 3.0)
(alt-profit 4.0)
(alt-profit 5.0)

