;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname Exercise-024-MovieTheatreV2) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp")))))
; Exercise 24. 
; Determine the potential profit for the following ticket prices: 
;         $1, $2, $3, $4, and $5.
; Which price should the owner of the movie theater choose to maximize his 
; profits? Determine the best ticket price down to a dime.

; Constants
(define AVG_ATTENDENCE    120)
(define BASE_TICKET_PRICE   5.0)
(define PEOPLE_SWING 15)
(define PRICE_VARIANCE 0.1)
(define FIXED_COSTS 180.0)
(define VARIABLE_COSTS 0.04)

; # of attendees is based on ticket price
(define (attendees ticket-price)  
  (- AVG_ATTENDENCE (* (- ticket-price BASE_TICKET_PRICE) 
                       (/ PEOPLE_SWING PRICE_VARIANCE))))

; revenue generated by ticket sales
(define (revenue ticket-price) 
  (* ticket-price (attendees ticket-price)))

; cost has a fixed part and a variable part based on the number of attendees
(define (cost ticket-price)  
  (+ FIXED_COSTS (* VARIABLE_COSTS (attendees ticket-price))))

; profit
(define (profit ticket-price) 
  (- (revenue ticket-price)     
     (cost ticket-price)))

(profit 1.0) ; 511.2
(profit 2.0) ; 937.2
(profit 3.0) ; 1063.2
(profit 4.0) ; 889.2
(profit 5.0) ; 415.2

; Below is an alternative version of the same program, given as a single 
; function definition of the above program; use it to check the values
; returned by the original.

(define (alt-profit price) 
  (- (* (+ 120 (* (/ 15 0.1) (- 5.0 price)))  price)
     (+ 180 (* 0.04 (+ 120 (* (/ 15 0.1) (- 5.0 price)))))))

(alt-profit 1.0) ; 511.2
(alt-profit 2.0) ; 937.2
(alt-profit 3.0) ; 1063.2
(alt-profit 4.0) ; 889.2
(alt-profit 5.0) ; 415.2

